# configuration for apisix(dp) to mock multi-replica deployment scenario to be used with
# config1.yaml present in the same directory as config0.yaml first added to prepare multi-dp
# scenario to test `sync_interval` feature in limit-count-redis and limit-count-redis-cluster

apisix:
  node_listen: 9081
  enable_ipv6: false

  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9093
deployment:
  admin:
    allow_admin:
      - 0.0.0.0/0
    admin_listen:
      ip: 0.0.0.0
      port: 9181
plugins:
  - limit-count
nginx_config:
  error_log: logs/error1.log
