version: "3.8"

services:
  apisix_redis:
    # The latest image is the latest stable version
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - api7

  graphql-demo:
    image: npalm/graphql-java-demo
    ports:
      - "8888:8080"
    networks:
      - api7

  soap-server:
    hostname: soap-server
    build:
      context: ci/pod/soap-server
      dockerfile: Dockerfile
    restart: always
    networks:
      - api7

  soap-proxy:
    hostname: soap-proxy
    build:
      context: ci/pod/soap-proxy
      dockerfile: Dockerfile
    restart: always
    ports:
      - "15001:5000"
    networks:
      - api7

  push-gateway:
    hostname: push-gateway
    container_name: api7-push-gateway
    image: hkccr.ccs.tencentyun.com/api7/api7-ee-push-gateway:1.1.1
    restart: always
    ports:
      - "9110:9110"
    networks:
      - api7

networks:
  api7:
    driver: bridge
    ipam:
      driver: default
