version: "3.8"

services:
  apisix_redis:
    # The latest image is the latest stable version
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - api7

  graphql-demo:
    image: npalm/graphql-java-demo
    ports:
      - "8888:8080"
    networks:
      - api7

networks:
  api7:
    driver: bridge
    ipam:
      driver: default
