version: "3.8"

services:
  apisix_redis:
    # The latest image is the latest stable version
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - api7

  graphql-demo:
    image: npalm/graphql-java-demo
    ports:
      - "8888:8080"
    networks:
      - api7

  soap-server:
    image: api7/soap-server
    hostname: soap-server
    restart: always
    networks:
      - api7

  soap-proxy:
    image: api7/soap-proxy:1.0.0
    hostname: soap-proxy
    restart: always
    ports:
      - "15001:5000"
    networks:
      - api7

networks:
  api7:
    driver: bridge
    ipam:
      driver: default
