name: Build docker images on commit and push them to registry
on:
  pull_request:
    branches:
      - main
    paths:
      - Dockerfile
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions: read-all
jobs:
  docker-images:
    strategy:
      matrix:
        runner: [buildjet-2vcpu-ubuntu-2204, buildjet-2vcpu-ubuntu-2204-arm]
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          submodules: recursive

      - name: Set image tag
        id: version
        run: |
          echo "IMAGE_TAG=`git rev-parse --short HEAD`-`TZ=Asia/Shanghai date '+%m%d%H%M'`" >> $GITHUB_OUTPUT

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
          username: ${{ secrets.PRIVATE_DOCKER_USERNAME }}
          password: ${{ secrets.PRIVATE_DOCKER_PASSWORD }}

      - name: Verify Dockerfile
        if: github.event_name == 'pull_request'
        env:
          REGISTRY: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
          REGISTRY_NAMESPACE: api7-dev
          IMAGE_TAG: dev
        run: |
          make build-image
        
      - name: Push Images With Dev Tag
        if: github.event_name == 'push'
        env:
          REGISTRY: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
          REGISTRY_NAMESPACE: api7-dev
          IMAGE_TAG: dev
        run: |
          make push-image

      - name: Push Images With Commit Tag
        if: github.event_name == 'push'
        env:
          REGISTRY: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
          REGISTRY_NAMESPACE: api7-dev
          IMAGE_TAG: ${{ steps.version.outputs.IMAGE_TAG }}
        run: |
          make push-image
    outputs:
      image_tag: ${{ steps.version.outputs.IMAGE_TAG }}

  docker-manifest:
    needs: docker-images
    runs-on: buildjet-2vcpu-ubuntu-2204
    if: github.event_name == 'push'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
          username: ${{ secrets.PRIVATE_DOCKER_USERNAME }}
          password: ${{ secrets.PRIVATE_DOCKER_PASSWORD }}

      - name: Create and push docker manifest
        env:
          REGISTRY: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
          REGISTRY_NAMESPACE: api7-dev
          IMAGE_TAG: dev
        run: |
          make docker-manifest

      - name: Create and push docker manifest
        env:
          REGISTRY: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
          REGISTRY_NAMESPACE: api7-dev
          IMAGE_TAG: ${{ needs.docker-images.outputs.image_tag }}
        run: |
          make docker-manifest
