name: Build docker images on commit and push them to registry
on:
  pull_request:
    branches:
      - main
    paths:
      - Dockerfile
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions: read-all
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          submodules: recursive

      - name: Set image tag
        run: |
          echo "IMAGE_TAG=`git rev-parse --short HEAD`-`TZ=Asia/Shanghai date '+%m%d%H%M'`" >> $GITHUB_ENV

      - name: Set VERSION image tag
        id: version
        run: |
          VERSION=$(cat ./apisix/core/version.lua | grep -o 'VERSION = "[^"]*"' | awk -F'"' '{print $2}')
          echo "GATEWAY_VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
          username: ${{ secrets.PRIVATE_DOCKER_USERNAME }}
          password: ${{ secrets.PRIVATE_DOCKER_PASSWORD }}

      - name: Build Images With Dev Tag
        if: github.event_name == 'pull_request'
        env:
          REGISTRY: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
          REGISTRY_NAMESPACE: api7-dev
          IMAGE_TAG: dev
        run: |
          make build-image
          docker save ${REGISTRY}/${REGISTRY_NAMESPACE}/api7-ee-3-gateway:${IMAGE_TAG} | gzip > api7-ee-3-gateway-dev.tar.gz
        
      - name: Upload Dev Dcoker Image
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: api7-ee-3-gateway-dev
          path: api7-ee-3-gateway-dev.tar.gz

      - name: Push Images With Dev Tag
        if: github.event_name == 'push'
        env:
          REGISTRY: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
          REGISTRY_NAMESPACE: api7-dev
          IMAGE_TAG: dev
        run: |
          make push-image

      - name: Push Images With Commit Tag
        if: github.event_name == 'push'
        env:
          REGISTRY: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
          REGISTRY_NAMESPACE: api7-dev
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          make push-image
