name: CLI Test

on:
  push:
    branches: [main, 'release/**']
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    types: [labeled, synchronize]
    branches: [main, 'release/**']
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: |
      contains(github.event.pull_request.labels.*.name, 'ci-cli') ||
      contains(github.event.pull_request.labels.*.name, 'ci-gateway-all') ||
      github.ref == 'refs/heads/main' ||
      github.ref == 'refs/heads/release'
    strategy:
      fail-fast: false
      matrix:
        platform:
          - buildjet-2vcpu-ubuntu-2004
        job_name:
          - linux_apisix_current_luarocks
          - linux_apisix_current_luarocks_in_customed_nginx

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    env:
      SERVER_NAME: ${{ matrix.job_name }}
      OPENRESTY_VERSION: default

    steps:
      - name: Fix Broken apt list
        run: |
          sudo rm -rf /var/lib/apt/lists/*
          sudo mkdir -p /var/lib/apt/lists/partial
          sudo apt clean
          sudo apt update

      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check out APISIX repo
        run: |
          make init_apisix
          make patch_apisix
          make install

      - name: Modify the files
        working-directory: workbench
        run: |
          sed -i 's/lua_module_hook/#lua_module_hook/' conf/config-default.yaml

      - name: Install dependent services
        run: |
          ./ci/utils/install-lua-resty-openapi-validate.sh
          ./ci/utils/install-lua-resty-aws-s3.sh
          ./ci/utils/install-lua-resty-azure-blob.sh
          ./ci/utils/linux-common-runnner.sh start_mock_heartbeat_server

      - name: Modify the files
        run: |
          cd workbench
          sed -i 's/API7\//APISIX\//' apisix/init.lua
          sed -i 's/lua_module_hook/#lua_module_hook/' conf/config-default.yaml
          sed -i 's/apisix-master-0.rockspec/api7-master-0.rockspec/' Makefile
          sed -i 's/apisix-master-0.rockspec/api7-master-0.rockspec/' ci/linux_apisix_current_luarocks_runner.sh
          sed -i 's/luarocks show apisix/luarocks show api7/' ci/linux_apisix_current_luarocks_runner.sh

      - name: Cache deps
        uses: actions/cache@v5
        env:
          cache-name: cache-deps
        with:
          path: deps
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ matrix.job_name }}-${{ hashFiles('workbench/rockspec/api7-master-0.rockspec') }}

      - name: Set hostname
        run: |
          sudo hostnamectl set-hostname ubuntu
          sudo sh -c 'echo "127.0.1.1   $(hostname)" >> /etc/hosts'
          sudo sh -c 'echo "127.0.0.1   httpbin.local" >> /etc/hosts'
          sudo sh -c 'echo "127.0.0.1   petstore3.local" >> /etc/hosts'

      - name: Linux launch common services
        working-directory: workbench
        run: |
          project_compose_ci=ci/pod/docker-compose.common.yml make ci-env-up
          project_compose_ci=ci/pod/docker-compose.limit-count.yml make ci-env-up

      - name: Linux Before install
        working-directory: workbench
        run: sudo ./ci/${{ matrix.job_name }}_runner.sh before_install

      - name: Linux Install
        working-directory: workbench
        run: |
            sudo --preserve-env=OPENRESTY_VERSION \
            ./ci/${{ matrix.job_name }}_runner.sh do_install
            sudo cp ../deps/* -r /usr/local/

      # The length of the working directory path for buildjet is too long,
      # which will exceed the operating system's limit for the complete path of apisix config_listen.sock.
      - name: Move workbench to /tmp
        run: |
          sudo mv ./workbench /tmp

      - name: Linux Script
        working-directory: /tmp/workbench
        run: |
          sudo ./ci/${{ matrix.job_name }}_runner.sh script
