name: Build And Push Release Private Docker Image
on:
  workflow_dispatch:

permissions: read-all
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release')
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          submodules: recursive

      - name: Set image tag
        id: version
        run: |
          VERSION=$(cat ./apisix/core/version.lua | grep -o 'VERSION = "[^"]*"' | awk -F'"' '{print $2}')
          echo "GATEWAY_VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Images
        run: |
          docker build -t api7-ee-3-gateway:dev .

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
          username: ${{ secrets.PRIVATE_DOCKER_USERNAME }}
          password: ${{ secrets.PRIVATE_DOCKER_PASSWORD }}

      - name: Push Images
        env:
          REGISTRY: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
          IMAGE_TAG: ${{ steps.version.outputs.GATEWAY_VERSION }}
        run: |
          docker tag api7-ee-3-gateway:dev $REGISTRY/api7/api7-ee-3-gateway:$IMAGE_TAG
          docker push $REGISTRY/api7/api7-ee-3-gateway:$IMAGE_TAG
