name: CI Kubernetes

on:
  push:
    branches: [main, 'release/**']
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    types: [labeled, synchronize]
    branches: [main, 'release/**']
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  kubernetes-discovery:
    if: |
      contains(github.event.pull_request.labels.*.name, 'ci-kubernetes') ||
      contains(github.event.pull_request.labels.*.name, 'ci-gateway-all') ||
      github.ref == 'refs/heads/main' ||
      github.ref == 'refs/heads/release'
    strategy:
      fail-fast: false
      matrix:
        platform:
          - buildjet-2vcpu-ubuntu-2004
        os_name:
          - linux_openresty

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    env:
      SERVER_NAME: ${{ matrix.os_name }}
      OPENRESTY_VERSION: default

    steps:
      - name: Check out code
        uses: actions/checkout@v3.2.0
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          submodules: recursive

      - name: Check out APISIX repo
        run: |
          make init_apisix
          make patch_apisix
          make install

      - name: Install lua-resty-openapi-validate
        run: |
          ./ci/utils/install-lua-resty-openapi-validate.sh

      - name: Modify the files
        working-directory: workbench
        run: |
          sed -i 's/API7\//APISIX\//' apisix/init.lua
          sed -i 's/lua_module_hook/#lua_module_hook/' conf/config-default.yaml
          sed -i 's/apisix-master-0.rockspec/api7-master-0.rockspec/' Makefile
          sed -i 's/apisix-master-0.rockspec/api7-master-0.rockspec/' ci/linux_apisix_current_luarocks_runner.sh
          sed -i 's/luarocks show apisix/luarocks show api7/' ci/linux_apisix_current_luarocks_runner.sh

      - name: Linux launch common services
        run: |
          cd workbench
          make ci-env-up project_compose_ci=ci/pod/docker-compose.common.yml

      - name: Setup kubernetes cluster
        working-directory: workbench
        run: |
          KUBERNETES_VERSION="v1.22.7"

          kind create cluster --name apisix-test --config ./t/kubernetes/configs/kind.yaml --image kindest/node:${KUBERNETES_VERSION}

          kubectl wait --for=condition=Ready nodes --all --timeout=180s

          kubectl apply -f ./t/kubernetes/configs/account.yaml

          kubectl apply -f ./t/kubernetes/configs/endpoint.yaml

          KUBERNETES_CLIENT_TOKEN_CONTENT=$(kubectl get secrets | grep apisix-test | awk '{system("kubectl get secret -o jsonpath={.data.token} "$1" | base64 --decode")}')

          KUBERNETES_CLIENT_TOKEN_DIR="/tmp/var/run/secrets/kubernetes.io/serviceaccount"

          KUBERNETES_CLIENT_TOKEN_FILE=${KUBERNETES_CLIENT_TOKEN_DIR}/token

          mkdir -p ${KUBERNETES_CLIENT_TOKEN_DIR}
          echo -n "$KUBERNETES_CLIENT_TOKEN_CONTENT" > ${KUBERNETES_CLIENT_TOKEN_FILE}

          echo 'KUBERNETES_SERVICE_HOST=127.0.0.1'
          echo 'KUBERNETES_SERVICE_PORT=6443'
          echo 'KUBERNETES_CLIENT_TOKEN='"${KUBERNETES_CLIENT_TOKEN_CONTENT}"
          echo 'KUBERNETES_CLIENT_TOKEN_FILE='${KUBERNETES_CLIENT_TOKEN_FILE}

          kubectl proxy -p 6445 &

      - name: Linux Install
        working-directory: workbench
        run: |
          sudo ./ci/${{ matrix.os_name }}_runner.sh before_install
          sudo --preserve-env=OPENRESTY_VERSION ./ci/${{ matrix.os_name }}_runner.sh do_install
          sudo cp ../deps/* -r /usr/local/

      # The length of the working directory path for buildjet is too long,
      # which will exceed the operating system's limit for the complete path of apisix config_listen.sock.
      - name: move workbech to /tmp
        run: |
          sudo mv ./workbench /tmp

      - name: Run test cases
        working-directory: /tmp/workbench
        run: |
          ./ci/kubernetes-ci.sh run_case
