name: ❄️ Lint

on:
  pull_request:
    types: [labeled, synchronize]
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

permissions:
  contents: read

jobs:
  misc:
    if: |
      contains(github.event.pull_request.labels.*.name, 'ci-3.2') ||
      contains(github.event.pull_request.labels.*.name, 'ci-gateway-all') ||
      github.ref == 'refs/heads/main'
    name: misc checker
    runs-on: buildjet-2vcpu-ubuntu-2004
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Check out APISIX repo
        run: |
          make init_apisix
          make patch_apisix
          make install

      - name: Modify the files
        working-directory: workbench
        run: |
          sed -i 's/API7\//APISIX\//' apisix/init.lua
          sed -i 's/lua_module_hook/#lua_module_hook/' conf/config-default.yaml
          sed -i 's/apisix-master-0.rockspec/api7-master-0.rockspec/' Makefile
          sed -i 's/apisix-master-0.rockspec/api7-master-0.rockspec/' ci/linux_apisix_current_luarocks_runner.sh
          sed -i 's/luarocks show apisix/luarocks show api7/' ci/linux_apisix_current_luarocks_runner.sh

      - name: spell check
        working-directory: workbench
        run: |
          pip install codespell==2.1.0
          # codespell considers some repo name in go.sum are misspelled
          git grep --cached -l '' | grep -v go.sum |xargs codespell --ignore-words=.ignore_words
      - name: Merge conflict
        working-directory: workbench
        run: |
          bash ./utils/check-merge-conflict.sh
      - name: Plugin Code
        working-directory: workbench
        run: |
          bash ./utils/check-plugins-code.sh

  ci-eclint:
    if: |
      contains(github.event.pull_request.labels.*.name, 'ci-3.2') ||
      contains(github.event.pull_request.labels.*.name, 'ci-gateway-all') ||
      github.ref == 'refs/heads/main'
    runs-on: buildjet-2vcpu-ubuntu-2004
    timeout-minutes: 40

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Check out APISIX repo
        run: |
          make init_apisix
          make patch_apisix
          make install
          cp ./.editorconfig ./workbench

      - name: Modify the files
        working-directory: workbench
        run: |
          sed -i 's/API7\//APISIX\//' apisix/init.lua
          sed -i 's/lua_module_hook/#lua_module_hook/' conf/config-default.yaml
          sed -i 's/apisix-master-0.rockspec/api7-master-0.rockspec/' Makefile
          sed -i 's/apisix-master-0.rockspec/api7-master-0.rockspec/' ci/linux_apisix_current_luarocks_runner.sh
          sed -i 's/luarocks show apisix/luarocks show api7/' ci/linux_apisix_current_luarocks_runner.sh

      - name: Setup Nodejs env
        uses: actions/setup-node@v4.0.1
        with:
            node-version: '12'

      - name: Install eclint
        run: |
          sudo npm install -g eclint

      - name: Run eclint
        working-directory: workbench
        run: |
          eclint check
