name: Build And Push Release Docker Image
on:
  push:
    tags:
      - "**"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions: read-all
jobs:
  docker-images:
    strategy:
      matrix:
        runner: [buildjet-2vcpu-ubuntu-2204, buildjet-2vcpu-ubuntu-2204-arm]
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          submodules: recursive

      - name: Set image tag
        id: version
        run: |
          VERSION=$(cat ./apisix/core/version.lua | grep -o 'VERSION = "[^"]*"' | awk -F'"' '{print $2}' | tr '+' '_')
          echo "GATEWAY_VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
          username: ${{ secrets.PRIVATE_DOCKER_USERNAME }}
          password: ${{ secrets.PRIVATE_DOCKER_PASSWORD }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push images to Docker Hub
        env:
          REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          REGISTRY_NAMESPACE: api7
          IMAGE_TAG: ${{ steps.version.outputs.GATEWAY_VERSION }}
        run: |
          make push-image

      - name: Push images to private registry
        env:
          REGISTRY: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
          REGISTRY_NAMESPACE: api7
          IMAGE_TAG: ${{ steps.version.outputs.GATEWAY_VERSION }}
        run: |
          make push-image
    outputs:
      image_tag: ${{ steps.version.outputs.GATEWAY_VERSION }}

  docker-manifest:
    needs: docker-images
    runs-on: buildjet-2vcpu-ubuntu-2204
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
          username: ${{ secrets.PRIVATE_DOCKER_USERNAME }}
          password: ${{ secrets.PRIVATE_DOCKER_PASSWORD }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and push docker manifest to private registry
        env:
          REGISTRY: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}
          REGISTRY_NAMESPACE: api7
          IMAGE_TAG: ${{ needs.docker-images.outputs.image_tag }}
        run: |
          make docker-manifest

      - name: Create and push docker manifest to Docker Hub
        env:
          REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          REGISTRY_NAMESPACE: api7
          IMAGE_TAG: ${{ needs.docker-images.outputs.image_tag }}
        run: |
          make docker-manifest
